### ISSUE TITLE
Invalid download link of the jar file

### ISSUE THREAD

**Issue by Lcram33** [ChenjieXu/pyzxing#2] opened 2020-07-25 15:34 UTC
Hello,

When installed with the pip command, the download link is invalid :
jar_url = "https://github.com/ChenjieXu/pyzxing/releases/download/v0.1/"
should be instead
jar_url = "https://github.com/ChenjieXu/pyzxing/releases/v0.1/"

Best regards

**Comment by ChenjieXu** [comment] 2020-07-28 02:11
The link with 'download' is correct. The actual download link is jar_url + jar_filename, which is "https://github.com/ChenjieXu/pyzxing/releases/download/v0.1/javase-3.4.1-SNAPSHOT-jar-with-dependencies.jar". The problem is I haven't upload this to pypi. It has been fixed in version 0.3.1.

**Closed by ChenjieXu** 2020-07-28 02:11 UTC
